name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.24.4'

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: '1.6.6' # or your preferred version

      - name: Install dependencies
        run: go mod download

      - name: Install golangci-lint
        run: |
          curl -sSfL https://raw.githubusercontent.com/golangci/golangci-lint/master/install.sh | sh -s -- -b $(go env GOPATH)/bin v1.54.2


      - name: Run linter
        run: golangci-lint run

      - name: Run tests
        run: go test ./...

      - name: Build CLI
        run: go build -o sorttf

      # Optionally, run your CLI tool on a test file to ensure terraform fmt is invoked
      - name: Test sorttf CLI with terraform fmt
        run: |
          echo 'resource "null_resource" "example" {}' > test.tf
          ./sorttf test.tf 